name: RDP Auto-Restart
on:
  schedule:
    # Har 6 ghante par run hoga
    - cron: '0 */6 * * *'

jobs:
  restart-rdp:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RDP Workflow
        run: |
          # Yeh 'rdp.yml' ko trigger karega (file name check kar lein)
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/rdp.yml/dispatches \
            -d '{"ref":"main"}'
